import styled from "styled-components";
import { useLocation } from 'react-router-dom';

const WeatherDiv = styled.div`
    padding: 25px;
    margin-bottom: 25px;
    font-size: 25px;
`;

const WeatherIconImg = styled.img`
    max-width: auto;
    height: 100px;
`;

const LocationDiv = styled.div`
    padding-bottom: 25px;

`;

const IconDiv = styled.div`
    padding-bottom: 20px;
`;

const TemperatureDiv = styled.div`
    padding-bottom: 20px;
`;

// Handles display of weather based on HTTP response.
export default function Weather() {
  const page = useLocation();
  const location = page.state?.temperature[0]; // API functions return value in array form, hence index, which is constant among all arrays generated by API functions.
  const temp = page.state?.temperature[1];
  const weather = page.state?.temperature[2];
  const weatherIconCode = page.state?.temperature[3];

  return (
    <WeatherDiv>
        <LocationDiv>
            {location ?? "Location Unavailable"}
        </LocationDiv>
        <IconDiv>
            {/* Handles event for when image cannot be generated (image not found within dir or location isn't found) */}
            <WeatherIconImg
                id="WeatherIcon"
                src={WeatherIcon(weatherIconCode)}
                alt="Restart Application"
                onError={(error) => {
                    error.target.onerror = null;
                    error.target.src = "/WeatherIcons/error.png";
                }}
            />
        </IconDiv>
        <TemperatureDiv>
            {temp ?? null}
        </TemperatureDiv>
        <div>
            {weather ?? null}
        </div>
    </WeatherDiv>
  );
}

// Function to output weather icon.
// More beneficial than having an abundance of conditional statements.
function WeatherIcon(weatherIconCode){
    if (weatherIconCode != null){
        const weatherIconPath = `/WeatherIcons/${weatherIconCode}.png`;
        return weatherIconPath; 
    } else {
        const weatherIconPath = `/WeatherIcons/error.png`;
        return weatherIconPath;  
    }
}